variables:
    cesUri:                 http://cwcc.compuware.com:2020
    hostUri:                cwcc.compuware.com
    hostPort:               16196
    hostCodePage:           1047
    topazCliWorkspace:      .\TopazCliWkspc
    ispwConfig:             ispw
    ccRepo:                 HDDRXM0.DEMO.COCO.REPOS
    ccSystem:               AZURE_$ispwSet
    ccTestid:               BUILD
    mfSourcesFolder:        MF_Source
    sonarProjectName:       RNU_$ispwApplication_GitLab
    sonarSources:           .\$ispwApplication\MF_Source
    tttEnvironment:         5b508b8a787be73b59238d38
    testFolderVt:           ./Virtualized_Tests
    testResultFolderVt:     ./TTTSonar/Virtualized_Tests.cli.suite.sonar.xml
    junitFile:              ./TTTUnit/Virtualized_Tests.cli.suite.junit.xml
    codeCoverageReportFile: ./Coverage/CodeCoverage.xml
    sonarUri:               http://dtw-sonarqube-cwcc.nasa.cpwr.corp:9000
    sonarProject:           RNU_FTSDEMO_GitLab

stages:
    - sonar

quality-gate:
    stage: sonar
    script: |
        $uri = $sonarUri'/api/qualitygates/project_status?projectKey='$sonarProject

        $headers = @{}
        $headers.Add("Authorization", '"'$sonarAuthorization'"')
        $headers.Add("Content-Type", "application/json")

        Write-Host "Checking Sonar Quality Gate Status for Project "$sonarProject"."
        Write-Host "URL"
        Write-Host $uri

        $response = Invoke-RestMethod -Uri $uri -method GET -headers $headers
        
        $status = $response.projectStatus.status
        
        Write-Host "Checked Sonar Quality Gate status for Project "$sonarProject"."
        Write-Host "Status is "$status"."
        
        if($status -ne "OK"){
            $LASTEXITCODE = 1
        }
        else
        {
            $LASTEXITCODE = 0
        }    