stages:
    - mf-sources

mf-sources:
    stage: mf-sources
    script: |
        echo "Getting Sources from Mainframe for"
        echo "Stream $ispwStream"
        echo "Application $ispwApplication"
        echo "Assignment $ispwAssignment"
        echo "Set $ispwSet"
        echo "Level $ispwSrcLevel"
        echo "Ownder $ispwOwner"