variables:
    hostUri:            cwcc.compuware.com
    hostPort:           16196
    hostCodePage:       1047
    topazCliWorkspace:  .\TopazCliWkspc
    ispwConfig:         ispw

stages:
    - mf-sources

mf-sources:
    stage: mf-sources
    variables:
        ispwTargetLevel: DEV1
    rules:
        - if: $ispwSrcLevel == 'DEV2'
          variables:
            ispwTargetLevel: DEV2
        - if: $ispwSrcLevel == 'DEV3'
          variables:
            ispwTargetLevel: DEV3
        - if: $ispwSrcLevel == 'FIX'
          variables:
            ispwTargetLevel: FIX
    script: |
        echo "Getting Sources from Mainframe for"
        echo "Stream $ispwStream"
        echo "Application $ispwApplication"
        echo "Assignment $ispwAssignment"
        echo "Set $ispwSet"
        echo "Source Level $ispwSrcLevel"
        echo "Target Level $ispwTargetLevel"
        echo "Ownder $ispwOwner"
        cmd.exe /c $cliPath'\SCMDownloaderCLI.bat -host '$hostUri' -port '$hostPort' -id '$hostUser' -pass '$hostPassword' -protocol None -code '$hostCodePage' -timeout 0 -targetFolder .\ -data '$topazCliWorkspace' -ispwServerConfig '$ispwConfig' -scm ispwc -ispwContainerName '$ispwSet' -ispwContainerType 2 -ispwServerLevel '$ispwTargetLevel' -ispwDownloadAll true'
    artifacts:
        paths: 
            - ./
        when: always